# Render Blueprint para Monday API Automation
# Desenvolvido por: Nathan Silva - Fagron Tech

services:
  - type: web
    name: monday-api-automation
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONDAY_API_TOKEN
        value: eyJhbGciOiJIUzI1NiJ9.eyJ0aWQiOjU0MDcxMzg4NCwiYWFpIjoxMSwidWlkIjo3NjMyOTgzOSwiaWFkIjoiMjAyNS0wNy0xOFQxNTowMzo1OS40NjRaIiwicGVyIjoibWU6d3JpdGUiLCJhY3RpZCI6MTE0OTc2MDksInJnbiI6InVzZTEifQ.Dyum-Id4xq8fuGeNPpVP05OhWdImu94DLBOvS8CWMWk
      - key: MONDAY_BOARD_ID
        value: "9572919643"
      - key: BASE_USER_PATH
        value: /tmp
      - key: MODEL_FILE_PATH
        value: /tmp/modelo.vsdx
    healthCheckPath: /health
    autoDeploy: true